spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-user-db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  application:
    name: ecommerce-user-service

  cloud:
    config:
      enabled: false